# Generated by Django 4.2 on 2026-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='min_weight',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=6, verbose_name='Minimal og‘irlik (kg)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_per_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Narxi/kg'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Skladdagi kg'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='weight_type',
            field=models.CharField(choices=[('unit', 'Dona'), ('kg', 'Kg')], default='unit', max_length=10, verbose_name='O‘lchov turi'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Og‘irlik (kg)'),
        ),
    ]
