# Generated by Django 5.0.7 on 2026-07-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_menuitem_min_weight_menuitem_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
        migrations.CreateModel(
            name='SavedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_data', models.JSONField(verbose_name="Chekni ma'lumoti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Saqlangan vaqti')),
                ('expires_at', models.DateTimeField(verbose_name="O'chish vaqti")),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_receipt', to='pos.order', verbose_name='Zakaz')),
            ],
            options={
                'verbose_name': 'Sozlama',
                'verbose_name_plural': 'Sozlamalar',
            },
        ),
    ]
