# Generated by Codex on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_settings_options_savedreceipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Sozlama', 'verbose_name_plural': 'Sozlamalar'},
        ),
        migrations.AlterModelOptions(
            name='savedreceipt',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Saqlangan chek',
                'verbose_name_plural': 'Saqlangan cheklar',
            },
        ),
        migrations.AlterField(
            model_name='savedreceipt',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name="O'chish vaqti"),
        ),
        migrations.AlterField(
            model_name='savedreceipt',
            name='order',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='saved_receipt',
                to='pos.order',
                verbose_name='Zakaz',
            ),
        ),
    ]
